### ISSUE TITLE
炸弹怎么出的？

### ISSUE THREAD

**Issue by Oeeder** [Kloping/landlord_game#1]
刚刚用了一下代码，发现炸弹出不来。
具体是要怎么出？
/出8888 这样子出不了炸弹。
是不是优先级的问题

**Comment by Oeeder** [comment]
以及目前好像还不支持飞机吧？
结束对局的时候也有点问题
![QQ截图20210917160325](https://user-images.githubusercontent.com/75010467/133747363-576b58f4-b978-4177-99d4-1d8d95eb2fa0.png)

**Comment by Kloping** [comment]
好的,会尽快修复的

**Comment by Oeeder** [comment]
炸弹的判定好像有点问题，炸弹应该是最大判定的吧，有时候炸弹拼不过单牌和三代一

**Comment by Kloping** [comment]
请尝试最新版
