### ISSUE TITLE
发牌之后就报错了，然后（强制）关闭对局也没有效果

### ISSUE THREAD

**Issue by Apurikotto** [Kloping/landlord_game#2]
![QQ截图20210920093515](https://user-images.githubusercontent.com/72537772/133948170-398822a0-ce8b-4798-b2a1-0e5dc77c7f3b.jpg)
![QQ截图20210920093712](https://user-images.githubusercontent.com/72537772/133948206-f13bf9aa-7aee-4715-b7d5-560f53b7cdcf.jpg)
如图。。

**Comment by Kloping** [comment]
> ![QQ截图20210920093515](https://user-images.githubusercontent.com/72537772/133948170-398822a0-ce8b-4798-b2a1-0e5dc77c7f3b.jpg)
> ![QQ截图20210920093712](https://user-images.githubusercontent.com/72537772/133948206-f13bf9aa-7aee-4715-b7d5-560f53b7cdcf.jpg)
> 如图。。

重新安装完整的jdk和最新的jar资源
